"""Method-card generation for the Phase 5 skeleton."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def render_method_card(config: dict[str, Any]) -> str:
    """Render a method card without empirical claims."""

    method = dict(config.get("method", {}))
    retrieval = dict(config.get("retrieval", {}))
    ablation = dict(config.get("ablation", {}))
    name = method.get("codename", "TimeGraphEvidenceRec")
    reportable = bool(method.get("reportable", False))
    modes = ", ".join(str(mode) for mode in retrieval.get("modes", []))
    switches = ", ".join(sorted(str(key) for key in ablation)) or "configured per ablation"
    return f"""# Method Card: Time-Aware Graph Evidence for LLM4Rec

## Purpose

`{name}` is a Phase 5 design skeleton for converting train-only temporal interaction graphs into grounded recommendation evidence. It is intended to test interfaces for sequence order, time gaps, time windows, transitions, contrastive evidence, and future dynamic graph encoders.

## What Is Original

The intended contribution direction is time-aware graph evidence for LLM4Rec: temporal transitions and interaction windows are represented as explicit evidence objects that can be scored, audited, translated into prompt-ready JSON, or passed to a future dynamic graph encoder.

## What Is Infrastructure

This Phase 5 implementation is infrastructure. It includes evidence contracts, retrieval, graph-to-text translation, deterministic smoke scoring, ablation switches, leakage checks, and method-card export. It does not claim final model performance.

## Required Inputs

- Train split interactions with user, item, timestamp, and domain fields.
- Item metadata for text/category signals.
- Candidate sets generated by the shared candidate protocol.
- A resolved experiment config with reportable status, seeds, split strategy, and output directory.

## Allowed Evidence

Evidence must be JSON serializable and must record provenance. Reportable runs may use only `constructed_from=train_only` artifacts. Supported evidence types are history, transition, time_window, time_gap, semantic, contrastive, and user_drift.

## Leakage Risks

The validator blocks target items in history, prompts containing target labels, reportable use of diagnostic-only artifacts, mock providers, stub encoders, and time-window evidence after the prediction timestamp.

## Ablation Switches

The skeleton supports config-driven switches: {switches}. The default retrieval modes are: {modes}.

## Reportable Status

Current reportable status: `{str(reportable).lower()}`. Phase 5 smoke outputs are non-reportable and must not be used as paper-scale results.

## Current Limitations

- Deterministic evidence-weight scoring is a smoke mechanism, not the final method.
- Phase 6 adds an optional lightweight `TemporalGraphEncoder` score path when a trained checkpoint is available. This encoder is not full TGN and remains smoke/sample validation infrastructure.
- No real API call, LoRA training, or paper-scale experiment is run in this phase.

## Future Extensions

Future work may replace the lightweight encoder with a full TGN/DGSR-style implementation while preserving the same evidence and evaluator contracts.

## Related Work Positioning

- G-Refer motivates graph evidence for explainable recommendation.
- Lost in Sequence motivates testing whether LLMs are sensitive to sequence order and temporal evidence.
- DGSR/TGN motivate dynamic graph representations for user/item states over time.

No empirical superiority is claimed by this method card.
"""


def write_method_card(config: dict[str, Any], output_path: str | Path) -> Path:
    """Write the method card and return its path."""

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_method_card(config), encoding="utf-8", newline="\n")
    return path
